### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by soupdiver** [iov-one/chatbot#13] opened 2019-09-02 08:48 UTC
When trying to build the code it fails with
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
```

Not sure if this is a temp problem or permanent. But it's not good to be unable to build the source.

**Comment by alpe** [comment] 2019-10-01 11:29
Thanks for reporting this issue. 🌷 
Unfortunately this project was not on my radar, so my response is a bit late. I hope the issue does not persist because I can not reproduce it. It worked on travis-CI and also on my local box when I run `make dist`.

I would close this issue now. Feel free to open it again or any new ticket for problems with the project.

**Closed as completed by alpe** 2019-10-01 11:29 UTC
